/** Sonic Adventure 2 City Escape Objects (Internal Names) */
export enum CityEscapeObjects {
    RING,
    RING_LINEAR,
    RING_CIRCLE,
    SPRA,
    SPRB,
    TRIPLESPRING,
    BIGJUMP,
    KASOKU,
    SAVEPOINT,
    SWITCH,
    ITEMBOX,
    ITEMBOXAIR,
    ITEMBOXBALLOON,
    LEVUPDAI,
    GOALRING,
    EMERALD,
    UDREEL,
    ORI,
    DYNAMITE,
    CONTWOOD,
    CONTIRON,
    ROCKET,
    ROCKETMISSSILE,
    SCHBOX,
    HINTBOX,
    MSGER,
    SSS,
    SOLIDBOX,
    DMYOBJ,
    SOAPSW,
    SKULL,
    PSKULL,
    CHAOPIPE,
    MINIMAL,
    WSMMLS,
    CONTCHAO,
    STOPLSD,
    KNUDAI,
    KDASIBA,
    KDWARPHOLE,
    KDDOOR,
    KDITEMBOX,
    KDDRNGL,
    KDDRNGC,
    KDSPRING,
    KDSPRINGB,
    SPHERE,
    CCYL,
    CCUBE,
    CWALL,
    CCIRCLE,
    MODMOD,
    EFFOBJ0,
    EFFLENSF,
    BUNCHIN,
    IRONBALL2,
    EKUMI,
    EAI,
    LIGHTSW,
    BOARDCOL,
    CARMAN,
    CARKAZ,
    TJUMPDAI,
    HAMMER,
    TRUCK,
    IRONBAR,
    TREEST,
    SWDRNGL,
    SWDRNGC,
    TREESHADOWS,
    LAMP,
    CARMANC,
    SIGNS,
    SIGNS_F,
    SBLG,
    ROADOBJ,
    PALM,
    BOARD,
    CARKAZ_S,
    SLIDER,
    GREEN_B,
    ADXCHG,
    BAR,
    FENCES,
    FENCEL,
    BIGTHECAT,
    SIGNBOARD,
    POSTER,
    TREESTNB,
    POSTER3,
    LINKLINK,
    EPATH,
    GUIDANCE,
    EGOLD,
    SARROW,
    TRBACK,
    CARMAN_NEAR,
    SE_PATCAR,
    SE_KAZE,
    POSTERM,
    NOINPCOL,
    PIC,
};

/* A Map of Sonic Adventure 2 Objects and their IDS */
export const OBJECT_TYPES = [
    ['Ring', CityEscapeObjects.RING],
    ['Line of Rings', CityEscapeObjects.RING_LINEAR],
    ['Circle of Rings', CityEscapeObjects.RING_CIRCLE],
    ['Spring', CityEscapeObjects.SPRA],
    ['Air Spring', CityEscapeObjects.SPRB],
    ['Triple Spring', CityEscapeObjects.TRIPLESPRING],
    ['Big Jump', CityEscapeObjects.BIGJUMP],
    ['Dash Panel', CityEscapeObjects.KASOKU],
    ['Save Point', CityEscapeObjects.SAVEPOINT],
    ['Ball Switch', CityEscapeObjects.SWITCH],
    ['Item Box', CityEscapeObjects.ITEMBOX],
    ['Floating Item Box', CityEscapeObjects.ITEMBOXAIR],
    ['Item Balloon', CityEscapeObjects.ITEMBOXBALLOON],
    ['Upgrade Item', CityEscapeObjects.LEVUPDAI],
    ['Goal Ring', CityEscapeObjects.GOALRING],
    ['Emerald', CityEscapeObjects.EMERALD],
    ['Pulley', CityEscapeObjects.UDREEL],
    ['Cage', CityEscapeObjects.ORI],
    ['Dynamite', CityEscapeObjects.DYNAMITE],
    ['Wood Box', CityEscapeObjects.CONTWOOD],
    ['Metal Box', CityEscapeObjects.CONTIRON],
    ['Rocket', CityEscapeObjects.ROCKET],
    ['Rocket Launch Pad', CityEscapeObjects.ROCKETMISSSILE],
    ['Hint Monitor', CityEscapeObjects.SCHBOX],
    ['Hint Box (Unused)', CityEscapeObjects.HINTBOX],
    ['Omochao', CityEscapeObjects.MSGER],
    ['Push/Pull Object (Unused)', CityEscapeObjects.SSS],
    ['Black Box', CityEscapeObjects.SOLIDBOX],
    ['Blank Object', CityEscapeObjects.DMYOBJ],
    ['Trigger Zone (Unused)', CityEscapeObjects.SOAPSW],
    ['Skull', CityEscapeObjects.SKULL],
    ['Skull (Immobile)', CityEscapeObjects.PSKULL],
    ['Animal Pipe', CityEscapeObjects.CHAOPIPE],
    ['Small Animal', CityEscapeObjects.MINIMAL],
    ['Whistle Area', CityEscapeObjects.WSMMLS],
    ['Chao Box', CityEscapeObjects.CONTCHAO],
    ['No Somersault Zone', CityEscapeObjects.STOPLSD],
    ['Mystic Shrine', CityEscapeObjects.KNUDAI],
    ['Shrine-activated Platform', CityEscapeObjects.KDASIBA],
    ['Shrine-activated Warp', CityEscapeObjects.KDWARPHOLE],
    ['Shrine-activated Door', CityEscapeObjects.KDDOOR],
    ['Shrine-activated Item Box', CityEscapeObjects.KDITEMBOX],
    ['Shrine-activated Line of Rings', CityEscapeObjects.KDDRNGL],
    ['Shrine-activated Circle of Rings', CityEscapeObjects.KDDRNGC],
    ['Shrine-activated Spring', CityEscapeObjects.KDSPRING],
    ['Shrine-activated Air Spring', CityEscapeObjects.KDSPRINGB],
    ['Sphere Collision', CityEscapeObjects.SPHERE],
    ['Cylinder Collision', CityEscapeObjects.CCYL],
    ['Cube Collision', CityEscapeObjects.CCUBE],
    ['Polygonal Collision', CityEscapeObjects.CWALL],
    ['Circular Collision', CityEscapeObjects.CCIRCLE],
    ['Shadows', CityEscapeObjects.MODMOD],
    ['Particle Generator', CityEscapeObjects.EFFOBJ0],
    ['Lens Flare', CityEscapeObjects.EFFLENSF],
    ['Moving Weight', CityEscapeObjects.BUNCHIN],
    ['Rotating Spike Balls', CityEscapeObjects.IRONBALL2],
    ['Beetle', CityEscapeObjects.EKUMI],
    ['Hunter', CityEscapeObjects.EAI],
    ['General Shade for Character Area', CityEscapeObjects.LIGHTSW],
    ['Snowboard Trigger Area', CityEscapeObjects.BOARDCOL],
    ['Moving Car 1', CityEscapeObjects.CARMAN],
    ['Stationary Car', CityEscapeObjects.CARKAZ],
    ['Trick Ramp', CityEscapeObjects.TJUMPDAI],
    ['Bobbing Hexagon Pillar', CityEscapeObjects.HAMMER],
    ['Truck Appearance Trigger', CityEscapeObjects.TRUCK],
    ['Swinging Pole', CityEscapeObjects.IRONBAR],
    ['Tree', CityEscapeObjects.TREEST],
    ['Switch-activated Line of Rings', CityEscapeObjects.SWDRNGL],
    ['Switch-activated Circle of Rings', CityEscapeObjects.SWDRNGC],
    ['Tree Shade for Character Area', CityEscapeObjects.TREESHADOWS],
    ['Decorative Lamp', CityEscapeObjects.LAMP],
    ['Moving Car 2', CityEscapeObjects.CARMANC],
    ['Decorative Street Signs', CityEscapeObjects.SIGNS],
    ['Decorative Street Signs (No Collision)', CityEscapeObjects.SIGNS_F],
    ['Big Billboard', CityEscapeObjects.SBLG],
    ['Decorative Object', CityEscapeObjects.ROADOBJ],
    ['Palm Tree', CityEscapeObjects.PALM],
    ['Snowboard Initial Position', CityEscapeObjects.BOARD],
    ['Stationary Car Small', CityEscapeObjects.CARKAZ_S],
    ['Somersault Entrance', CityEscapeObjects.SLIDER],
    ['Green Bush', CityEscapeObjects.GREEN_B],
    ['Music Change Trigger', CityEscapeObjects.ADXCHG],
    ['Swinging Bar Generator', CityEscapeObjects.BAR],
    ['Small Fence', CityEscapeObjects.FENCES],
    ['Large Fence', CityEscapeObjects.FENCEL],
    ['Big The Cat', CityEscapeObjects.BIGTHECAT],
    ['Billboard', CityEscapeObjects.SIGNBOARD],
    ['Poster 1', CityEscapeObjects.POSTER],
    ['Tree Alternate', CityEscapeObjects.TREESTNB],
    ['Poster 2', CityEscapeObjects.POSTER3],
    ['Trick Points Trigger', CityEscapeObjects.LINKLINK],
    ['Moving Beetle', CityEscapeObjects.EPATH],
    ['Arrow Guidance Barrier', CityEscapeObjects.GUIDANCE],
    ['Gold Beetle', CityEscapeObjects.EGOLD],
    ['Arrow Guidance', CityEscapeObjects.SARROW],
    ['Tree Tops', CityEscapeObjects.TRBACK],
    ['Moving Car 3', CityEscapeObjects.CARMAN_NEAR],
    ['Police Siren Sound Effect', CityEscapeObjects.SE_PATCAR],
    ['Wind Sound Effect', CityEscapeObjects.SE_KAZE],
    ['Poster 3', CityEscapeObjects.POSTERM],
    ['No Input Area', CityEscapeObjects.NOINPCOL],
    ['Tire', CityEscapeObjects.PIC],
];
