// Stage information found at:];
// https://docs.google.com/spreadsheets/d/1ShP3eTRoYKhqAZhSuecLgZmwRibp96bLbN-viI7QrXU/edit#gid=0

import { SA2Object } from "./objects";

/** A Map from an SA2Object to CityEscapeObjectID. */
export const CITY_ESCAPE_OBJECTS = new Set<SA2Object>([
    SA2Object.RING,
    SA2Object.RING_LINEAR,
    SA2Object.RING_CIRCLE,
    SA2Object.SPRA,
    SA2Object.SPRB,
    SA2Object.TRIPLESPRING,
    SA2Object.BIGJUMP,
    SA2Object.KASOKU,
    SA2Object.SAVEPOINT,
    SA2Object.SWITCH,
    SA2Object.ITEMBOX,
    SA2Object.ITEMBOXAIR,
    SA2Object.ITEMBOXBALLOON,
    SA2Object.LEVUPDAI,
    SA2Object.GOALRING,
    SA2Object.EMERALD,
    SA2Object.UDREEL,
    SA2Object.ORI,
    SA2Object.DYNAMITE,
    SA2Object.CONTWOOD,
    SA2Object.CONTIRON,
    SA2Object.ROCKET,
    SA2Object.ROCKETMISSSILE,
    SA2Object.SCHBOX,
    SA2Object.HINTBOX,
    SA2Object.MSGER,
    SA2Object.SSS,
    SA2Object.SOLIDBOX,
    SA2Object.DMYOBJ,
    SA2Object.SOAP_SW,
    SA2Object.SKULL,
    SA2Object.PSKULL,
    SA2Object.CHAOPIPE,
    SA2Object.MINIMAL,
    SA2Object.WSMMLS,
    SA2Object.CONTCHAO,
    SA2Object.STOPLSD,
    SA2Object.KNUDAI,
    SA2Object.KDASIBA,
    SA2Object.KDWARPHOLE,
    SA2Object.KDDOOR,
    SA2Object.KDITEMBOX,
    SA2Object.KDDRNGL,
    SA2Object.KDDRNGC,
    SA2Object.KDSPRING,
    SA2Object.KDSPRINGB,
    SA2Object.SPHERE,
    SA2Object.CCYL,
    SA2Object.CCUBE,
    SA2Object.CWALL,
    SA2Object.CCIRCLE,
    SA2Object.MODMOD,
    SA2Object.EFFOBJ0,
    SA2Object.EFFLENSF,
    SA2Object.BUNCHIN,
    SA2Object.IRONBALL2,
    SA2Object.E_KUMI,
    SA2Object.E_AI,
    SA2Object.LIGHT_SW,
    SA2Object.BOARDCOL,
    SA2Object.CARMAN,
    SA2Object.CARKAZ,
    SA2Object.TJUMPDAI,
    SA2Object.HAMMER,
    SA2Object.TRUCK,
    SA2Object.IRONBAR,
    SA2Object.TREEST,
    SA2Object.SWDRNGL,
    SA2Object.SWDRNGC,
    SA2Object.TREESHADOWS,
    SA2Object.LAMP,
    SA2Object.CARMANC,
    SA2Object.SIGNS,
    SA2Object.SIGNS_F,
    SA2Object.SBLG,
    SA2Object.ROADOBJ,
    SA2Object.PALM,
    SA2Object.BOARD,
    SA2Object.CARKAZ_S,
    SA2Object.SLIDER,
    SA2Object.GREEN_B,
    SA2Object.ADXCHG,
    SA2Object.BAR,
    SA2Object.FENCES,
    SA2Object.FENCEL,
    SA2Object.BIG_THE_CAT,
    SA2Object.SIGNBOARD,
    SA2Object.POSTER,
    SA2Object.TREESTNB,
    SA2Object.POSTER3,
    SA2Object.LINKLINK,
    SA2Object.E_PATH,
    SA2Object.GUIDANCE,
    SA2Object.E_GOLD,
    SA2Object.SARROW,
    SA2Object.TRBACK,
    SA2Object.CARMAN_NEAR,
    SA2Object.SE_PATCAR,
    SA2Object.SE_KAZE,
    SA2Object.POSTERM,
    SA2Object.NOINPCOL,
    SA2Object.PIC,
]);

/** Map from level id to objList. */
export const SA2_LEVELS = new Map<number, Set<SA2Object>>([
    [13, CITY_ESCAPE_OBJECTS],
]);
